#!/usr/bin/env python3
"""
Install a couple of variants of Python
using the Python.org installers
"""
import dataclasses
import typing
import pathlib
import shutil
import urllib.request
import tempfile
import hashlib
import plistlib
import subprocess
import os

PYTHON_FRAMEWORK = pathlib.Path("/Library/Frameworks/Python.framework")


#
# Note: The info contains an md5 checksum because that's what mentioned
#       on the download page on www.python.org.  Should be fine because
#       the checksum is primairily used to detect download problems.
@dataclasses.dataclass
class PythonInfo:
    url: str
    md5: typing.Optional[str] = None
    variant: typing.Optional[str] = None


PYTHONS = [
    PythonInfo(
        url="https://www.python.org/ftp/python/3.9.13/python-3.9.13-macos11.pkg",
        md5="76b63cf623e32cdf27c5033434bd69ce",
    ),
    PythonInfo(
        url="https://www.python.org/ftp/python/3.10.11/python-3.10.11-macos11.pkg",
        md5="f5f791f8e8bfb829f23860ab08712005",
    ),
    PythonInfo(
        url="https://www.python.org/ftp/python/3.11.9/python-3.11.9-macos11.pkg",
        md5="fa29f456feb6b5c4f52456a8b8ba347b",
    ),
    PythonInfo(
        url="https://www.python.org/ftp/python/3.12.8/python-3.12.8-macos11.pkg",
        md5="dc762fdc78e9cfecf516db31054de9fd",
    ),
    PythonInfo(
        url="https://www.python.org/ftp/python/3.13.1/python-3.13.12-macos11.pkg",
        md5="19e5a1d9e8264c88706ac9604c526e9b",
    ),
    PythonInfo(
        url="https://www.python.org/ftp/python/3.14.0/python-3.14.0a3-macos11.pkg",
        md5="2007a35ff5c90597bce6baf04cafd375",
    ),
]


def remove_pythons() -> None:
    if PYTHON_FRAMEWORK.exists():
        print(f"* Removing {PYTHON_FRAMEWORK}")
        shutil.rmtree(PYTHON_FRAMEWORK)


def have_download(path: pathlib.Path, md5: str) -> bool:
    if not path.exists():
        return False

    with open(path, "rb") as fp:
        h = hashlib.md5()
        while True:
            block = fp.read(128 * 1024)
            if not block:
                break
            h.update(block)

        return h.hexdigest() == md5


def download(
    url: str, md5: typing.Optional[str], directory: pathlib.Path
) -> pathlib.Path:
    fn = os.path.basename(url)
    installer_path = directory / fn
    if md5 is not None and have_download(installer_path, md5):
        print(f"* Use cached {url!r}")
        return installer_path

    print(f"* Downloading {url!r}")
    with urllib.request.urlopen(url) as fp_in:
        with open(installer_path, "wb") as fp_out:
            try:
                while True:
                    block = fp_in.read(128 * 1024)
                    if not block:
                        break
                    fp_out.write(block)
            except:  # noqa: E722
                os.unlink(fp_out.name)
                raise
    return installer_path


def install_certify(prefix: pathlib.Path) -> None:
    """
    Adapted from the "Install Certificates.command" file
    in a normal installation. This file won't be installed
    because this script doesn't install the GUI applications

    This function runs outside of the installed python, making
    it slightly more cumbersome to inspect the installation.
    """
    subprocess.check_call(
        [
            prefix / "bin" / "python3",
            pathlib.Path(__file__).parent / "install-certificates.py",
        ]
    )


def install_basic(prefix: pathlib.Path) -> None:
    subprocess.check_call(
        [
            prefix / "bin" / "python3",
            "-m",
            "pip",
            "install",
            "-U",
            "pip",
            "setuptools",
            "wheel",
        ]
    )


def install_python(installer_path: pathlib.Path, variant: typing.Optional[str]) -> None:
    """
    Perform an installation of Python, move to a variant directory if specified

    This will only install the framework itself with pip and won't
    install GUI tools or stuff in /usr/local.
    """
    version = installer_path.name.split("-")[1]
    version = ".".join(version.split(".")[:2])
    print(f"* Installing {version} from {installer_path}")
    config_bytes = subprocess.check_output(
        ["installer", "-showChoiceChangesXML", "-pkg", str(installer_path)]
    )
    config = plistlib.loads(config_bytes)

    # Update the configuration
    to_enable = {
        "org.python.Python.PythonFramework-",
        "org.python.Python.PythonInstallPip-",
        "org.python.Python.PythonTFramework-",
    }
    for item in config:
        if item["choiceAttribute"] != "selected":
            continue
        if any(item["choiceIdentifier"].startswith(nm) for nm in to_enable):
            item["attributeSetting"] = 1
        else:
            item["attributeSetting"] = 0

    # Install using updated configuration
    with tempfile.NamedTemporaryFile() as stream:
        plistlib.dump(config, stream, fmt=plistlib.FMT_XML)
        stream.flush()

        subprocess.check_call(
            [
                "installer",
                "-applyChoiceChangesXML",
                stream.name,
                "-pkg",
                str(installer_path),
                "-target",
                "/",
            ]
        )

    # Post-install: ensure certify is installed
    install_certify(PYTHON_FRAMEWORK / "Versions" / version)

    # Install or upgrade some packages
    install_basic(PYTHON_FRAMEWORK / "Versions" / version)

    # Variant update
    if variant is not None:
        (PYTHON_FRAMEWORK / "Versions" / version).rename(
            PYTHON_FRAMEWORK / "Versions" / f"{version}-{variant}"
        )


def main() -> None:
    directory = pathlib.Path(__file__).parent / "downloads"
    if not directory.exists():
        directory.mkdir()

    remove_pythons()

    for info in PYTHONS:
        installer_file = download(info.url, info.md5, directory)

        install_python(installer_file, info.variant)

    seen = set()
    for child in reversed(list((PYTHON_FRAMEWORK / "Versions").iterdir())):
        if "-" in child.name:
            base = child.name.split("-")[0]
            if base in seen:
                continue
            seen.add(base)
            print(f"* link {child.name} to {base}")
            os.symlink(child.name, PYTHON_FRAMEWORK / "Versions" / base)


if __name__ == "__main__":
    main()
